### ISSUE TITLE
cess.sh file lose execute file name

### ISSUE THREAD

**Issue by yiranone** [CESSProject/cess-nodeadm#10]
Maybe an error exist In the file cess.sh line 98 which lose execute file name "./cess-bucket" lead to run command fail. 

cess bucket increase 5000
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "increase": executable file not found in $PATH: unknown.

which In the file is
```
local cmd="docker run --rm --network=host $volumes $bucket_image"
```
Should be 
```
local cmd="docker run --rm --network=host $volumes $bucket_image ./cess-bucket "
```

**Comment by 0xbillw** [comment]
Thank you very much for your feedback! 

It is even better if you can provide the `cess version` command execution result.
But I guess the cause of this problem is that your version of the _cess-nodeadm_ program is not updated but pulls the latest image of the _cess-bucket_; The new _cess-bucket_ image has changed, and the old _cess-nodeadm_ program will have problems.

Yesterday we released CESS testnet 0.7 (rebooting the entire network). The solution to this issue is to download the latest version of _cess-nodeadm_ (currently v0.4.2) and execute the following commands:
```shell
# cd to the cess-nodeadm directory you just downloaded and run with sudo permissions
cess down  # Stop and remove services
cess purge  # Wipe old program data because the network is rebooted
./install.sh --skip-dep --retain-config  # Update only the cess-nodeadm program itself, and do not reset the configuration
cess config generate  # Regenerate the configuration
cess pullimg  # Update images
cess version  # Show the node current version
cess start
```
